services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    platform: linux/amd64
    ports:
      - "2181:2181"
    networks:
      - kafka-net

#  eureka:
#    image: spartans1179/euraka
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    environment:
#      EUREKA_CLIENT_REGISTER_WITH_EUREKA: 'false'
#      EUREKA_CLIENT_FETCH_REGISTRY: 'false'

  kafka:
    image: wurstmeister/kafka:latest
    platform: linux/amd64
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge

volumes:
  mongo_data:
    driver: local